
kind: Deployment #指定要创建的资源类型
apiVersion: apps/v1beta2 #获取官方的api
metadata:
  name: nginx-qman-d #创建的deploy名字
spec:
    replicas: 2 #创建的pod数量
    selector:
      matchLabels: #要匹配的标签
        app: nginx-qman
    template:
      metadata:
        labels: #pod标签
          app: nginx-qman #与上要一致
      spec:
        containers: #容器部分
          - name: nginx-qman-c #描述这个部分的文字
            image: nginx:latest #指定镜像
        ports:
          - containerPort: 80 #容器端口