apiVersion: v1
kind: Secret
metadata:
  name: ceph-secret
data:
  key: QVFEeE8waGJENzA4TkJBQVEyK3dlRlVMb3FZOElvbXRrNGRtRWc9PQ==


---

apiVersion: v1
kind: Pod
metadata:
  name: cephfs-test
spec:
  containers:
  - name: cephfs-test
    image: nginx
    volumeMounts:
    - mountPath: "/cephfs"
      name: cephfs
  volumes:
  - name: cephfs
    cephfs:
      monitors:
      - '10.1.62.173:6789'
      user: admin
      secretRef:
        name: ceph-secret
      readOnly: true
