apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mynginx
  namespace: sy
spec:
  serviceName: "mynginx"
  replicas: 1
  template:
    metadata:
      labels:
        app: mynginx
    spec:
      containers:
      - name: mynginx
        image: nginx
        command:
          - "/bin/sh"
        args:
          - "-c"
          - "sleep 3600"
        ports:
        - containerPort: 80
          name: mynginx
        volumeMounts:
        - name: mynginx-www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: mynginx-www
    spec:
      storageClassName: uat-rbd-kubeuat
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi