kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rbd-pvc-paycenter
  namespace: dev
spec:
  storageClassName: rbd-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi