# apiVersion: v1
# kind: Secret
# metadata:
#   name: ceph-secret-test2
#   namespace: default
# type: "kubernetes.io/rbd"  
# data:
#   key: QVFEeE8waGJENzA4TkJBQVEyK3dlRlVMb3FZOElvbXRrNGRtRWc9PQ==


---

# apiVersion: v1
# kind: Pod
# metadata:
#   name: rbd2
#   namespace: default
# spec:
#   containers:
#     - image: nginx
#       name: rbd-rw
#       volumeMounts:
#       - name: rbdpd
#         mountPath: /mnt/rbd
#   volumes:
#     - name: rbdpd
#       rbd:
#         monitors: 
#         - '10.1.62.173:6789'
#         pool: testpool
#         image: testimage
#         fsType: ext4
#         readOnly: false
#         user: admin
#         secretRef:
#           name: ceph-secret-test2

---

kind: Deployment 
apiVersion: apps/v1beta2 
metadata:
  name: rbd2-deployment 
  namespace: default
spec:
  replicas: 1
  selector:
      matchLabels: # @1 要匹配的标签,与@2 要保持一致
        app: rbd2
  strategy:
    rollingUpdate: 
      maxSurge: 1      #滚动升级时会先启动1个pod
      maxUnavailable: 1 #滚动升级时允许的最大Unavailable的pod个数
  template:
    metadata:
      labels: 
        app: rbd2 # @2 与上面 @1 要保持一致
    spec:
      containers:
        - image: nginx
          name: rbd-rw
          volumeMounts:
          - name: rbdpd
            mountPath: /mnt/rbd
      volumes:
        - name: rbdpd
          rbd:
            monitors: 
            - '10.1.62.173:6789'
            pool: testpool
            image: testimage
            fsType: ext4
            readOnly: true
            user: admin
            secretRef:
              name: ceph-secret-test2


---

kind: Deployment 
apiVersion: apps/v1beta2 
metadata:
  name: rbd3-deployment 
  namespace: default
spec:
  replicas: 1
  selector:
      matchLabels: # @1 要匹配的标签,与@2 要保持一致
        app: rbd3
  strategy:
    rollingUpdate: 
      maxSurge: 1      #滚动升级时会先启动1个pod
      maxUnavailable: 1 #滚动升级时允许的最大Unavailable的pod个数
  template:
    metadata:
      labels: 
        app: rbd3 # @2 与上面 @1 要保持一致
    spec:
      containers:
        - image: nginx
          name: rbd-rw3
          volumeMounts:
          - name: rbdpd3
            mountPath: /mnt/rbd
      volumes:
        - name: rbdpd3
          rbd:
            monitors: 
            - '10.1.62.173:6789'
            pool: testpool
            image: testimage
            fsType: ext4
            readOnly: true
            user: admin
            secretRef:
              name: ceph-secret-test2
